
    var petdatas = [
      {
          name: "拉布拉多",
          type: "dog",
          personality: "喜歡工作又聰明，即使受到挫折也很乖順。",
          feature: "本犬種屬於中等體形，只要平常多加管理，不太需要整理被毛，是一種容易飼養的犬種。",
          color: "毛色為黑色、黃色、巧克力色等，無斑紋。",
          img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRTfsRV8evxMVeJTJP9xtTnHkUnL6EzxGY5QiG8qNuuhVKKS2OqQA"
      }, {
          name: "雪納瑞",
          type: "dog",
          personality: "是開朗活潑的犬種，喜歡與人親近，個性勇敢堅强。",
          feature: "成犬之後顏色比幼犬更深。",
          color: "毛色一般為由灰色，此外也有黑色以及黑銀色。",
          img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSsAIMcn9gou8-bW5Ci7R6Zk-rUAEeBKFVThqgXY-3FOq7vJvDf"
      }, {
          name: "米格魯",
          type: "dog",
          personality: "活潑，非常適合飼養為家犬，體形雖不大但動作卻很迅速，但其吠聲非常高亢必須特別注意。",
          feature: "嗅覺敏銳、吠聲高亢",
          color: "毛質屬於滑順的短毛，毛色為白色、黑色、黃褐色、白色夾雜檸檬色等皆可。",
          img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTTAFO1OY7CioNpOweeSCHr4TSefhAAMu_Qbp0PBamsWlS5KQXe"
      }, {
          name: "威爾斯柯基犬",
          type: "dog",
          personality: "洋溢著活潑的氣息，並且很聰明，屬於個性爽朗的犬種。",
          feature: "雙耳直立，瞼部無顯著，耳朵前端尖銳，身高很高，頭部稍大。",
          color: "有紅色、黑貂色、淡紅褐色、黑色等",
          img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQwpXlzpTBfYZ2WjgjomghnkQwwbMkrLg1tdbBTMWofU5A9_BBQyw"
      }, {
          name: "柴犬",
          type: "dog",
          personality: "忠於主人，感覺敏銳、勇敢，而且不會亂吠。",
          feature: "動作很敏捷，不厭寒暑，身體很强健。",
          color: "上被毛為筆直的鋼毛，很堅硬。毛色為紅色、芝蔴色、虎斑色與白色等。",
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjcTtuul0OHjAs6Rx1Xlazs50tfwsBR20m0kWHOs5ybuB6MD78"
      }, {
          name: "博美犬",
          type: "dog",
          personality: "活潑好動 心胸開朗。",
          feature: "小耳挺立，亮麗的眼晴給人可愛的印象。尾巴覆蓋在背上，身上的毛膨鬆可愛。",
          color: "具光澤的上毛與短下毛，黃褐色、奶油色、橘色等。",
          img: "https://scontent-tpe1-1.xx.fbcdn.net/v/t1.0-0/p206x206/15541248_10207979238184048_1372971477319696988_n.jpg?oh=ddb62e0bc30f2354574f4901a2fc0a0c&oe=5944E0AB"
      }, {
          name: "日本短尾貓",
          type: "cat",
          personality: "平和的性格和溫馴",
          feature: "捲曲的尾巴全長5一10公分。頭部的頰骨高、鼻子長;眼睛為上揚的圓卵型。體型結實、肌肉十分發達。",
          color: "點狀和刺鼠虎斑外的所有毛色均為白色",
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRup1qgSpCE7MLE_bbowNg0euVyGvFyTOBSVsbl9BDFO7_bSwBGfQ"
      }, {
          name: "東方長毛貓",
          type: "cat",
          personality: "調皮、依賴",
          feature: "頭部呈V字型，有一雙大耳朵和杏眼，體型十分流暢且優美，身軀纖細，尾巴長如鞭。",
          color: "點狀和刺鼠虎斑外的所有毛色均為白色",
          img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSzKnlGXgF97kLx7Rh5hjrGZzA1QfUaVkE0KC4G6UXU_Sbv4JUJ"
      }, {
          name: "雪鞋貓",
          type: "cat",
          personality: "安靜、很喜歡人類",
          feature: "肌肉發達、身軀細長、四肢也很修長。末端變細的尾巴和身軀等長，表現出良好平衡感。",
          color: "白色 體毛光滑。",
          img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS98rUThC_awSriHKPsBHDcwv6QKY-TmJJYKphl0CnZCTWbhXMcjA"
      }, {
          name: "新加普拉貓",
          type: "cat",
          personality: "溫和、愛撒嬌，且好奇心強，動作敏捷",
          feature: "比例勻稱。頭部又圓又小，眼下的位置有條紋。下顎、胸部、腹部為苔綠色。",
          color: "柔軟的短體毛叢生體表，黑貂刺鼠虎斑色。",
          img: "http://101570310.weebly.com/uploads/1/5/7/3/15735300/3283089_orig.jpg"
      }, {
          name: "美國短毛貓",
          type: "cat",
          personality: "活潑、溫和、穩重",
          feature: "具有彈性的四肢和健壯的身軀，頭部為帶有圓形感的長方形，眼睛又大又圓有上揚感。",
          color: "銀白色和黑色的古典虎斑。",
          img: "http://101570310.weebly.com/uploads/1/5/7/3/15735300/9606179_orig.jpg"
      }, {
          name: "挪威森林貓",
          type: "cat",
          personality: "溫馴、服從",
          feature: "耳朵位在頭部的低處，臉型為扁平的三角形。胸部四周的肌肉特別發達 後肢比前肢長。",
          color: "白色 黑色和虎斑等。下毛十分柔軟，上毛較硬",
          img: "http://101570310.weebly.com/uploads/1/5/7/3/15735300/6285319.jpg?124"
      }, {
          name: "環頸鸚鵡",
          type: "bird",
          personality: "活潑、好奇",
          feature: "雄鳥頸部呈環狀頸紋，環頸鸚鵡適應能力佳，活潑、好奇心強，6個月大起可學說話，易飼養、易與人親近。",
          color: "原生種是綠色，黃、藍、白色是常見變種。",
          img: "http://blog.sina.com.tw/myimages/1/118785/images/20111013094611886.jpg"
      }, {
          name: "虎皮鸚鵡",
          type: "bird",
          personality: "好伺候、好動",
          feature: "頭部呈圓，喙部有鉤曲，腿較短，有兩腳趾向前，兩腳趾向後，易於攀樹、攀物。",
          color: "羽毛呈黃色且有黑色條紋。",
          img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Budgerigar-strzelecki-qld.jpg/250px-Budgerigar-strzelecki-qld.jpg"
      }, {
          name: "綠頰錐尾鸚鵡",
          type: "bird",
          personality: "調皮、活潑、好奇、親人",
          feature: "對人的接受度高，安靜又討喜，所以很適合各種居家環境飼養。",
          color: "體色較淡較亮，胸前呈灰色，尾部是紅褐色。",
          img: "http://www.ichong123.com/uploads/2015/8/1263.jpg"
      }, {
          name: "雀和金絲雀",
          type: "bird",
          personality: "膽子小、警覺性高",
          feature: "體型飽滿結實，目光炯炯有神，愛啼叫，聲音清脆不間斷。",
          color: "羽毛光亮鮮明柔順。",
          img: "../Content/Images/bird1.jpg"
      }, {
          name: "八哥鳥",
          type: "bird",
          personality: "性情溫馴、消化力極強",
          feature: "生性非常怕冷，善於觀察周遭的變化。",
          color: "黑色而有光澤。",
          img: "../Content/Images/bird2.jpg"
      }, {
          name: "白頭翁",
          type: "bird",
          personality: "活潑、好動",
          feature: "善於鳴叫，而且聲音婉轉多變化。",
          color: "頭黑枕部白，背部為黃綠色，胸部大多都是灰褐色，腹部為白色。",
          img: "../Content/Images/bird3.jpg"
      }

    ];
    var vm = new Vue({
        el: "#app",
        data: {
            mode_type: "false",
            mode_detail: true,
            pets: petdatas
        }
    });
