//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjPetAdoption.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aniDataPicOne
    {
        public int animalID { get; set; }
        public string animalName { get; set; }
        public string animalKind { get; set; }
        public string animalType { get; set; }
        public string animalColor { get; set; }
        public string animalGender { get; set; }
        public string animalDate { get; set; }
        public string animalAddress { get; set; }
        public Nullable<int> animalAge { get; set; }
        public string animalOwner_userID { get; set; }
        public string animalGetter_userID { get; set; }
        public string animalAdopted { get; set; }
        public string animalPicAddress { get; set; }
    }
}
