//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjPetAdoption.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class animalData_Condition
    {
        public int conditionID { get; set; }
        public Nullable<int> condition_animalID { get; set; }
        public string conditionAge { get; set; }
        public string conditionEconomy { get; set; }
        public string conditionHome { get; set; }
        public string conditionFamily { get; set; }
        public string conditionReply { get; set; }
        public string conditionPaper { get; set; }
        public string conditionFee { get; set; }
        public string conditionOther { get; set; }
    
        public virtual animalData animalData { get; set; }
    }
}
