//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjPetAdoption.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAnimal : DbContext
    {
        public DbAnimal()
            : base("name=DbAnimal")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<animalData> animalData { get; set; }
        public virtual DbSet<animalData_Condition> animalData_Condition { get; set; }
        public virtual DbSet<animalData_Pic> animalData_Pic { get; set; }
        public virtual DbSet<animalData_Type> animalData_Type { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<board> board { get; set; }
        public virtual DbSet<follow> follow { get; set; }
        public virtual DbSet<forum> forum { get; set; }
        public virtual DbSet<forum_reply> forum_reply { get; set; }
        public virtual DbSet<map> map { get; set; }
        public virtual DbSet<Msg> Msg { get; set; }
        public virtual DbSet<petFAQ> petFAQ { get; set; }
        public virtual DbSet<petKnows> petKnows { get; set; }
        public virtual DbSet<petTodo> petTodo { get; set; }
        public virtual DbSet<remind> remind { get; set; }
        public virtual DbSet<search> search { get; set; }
        public virtual DbSet<shelter> shelter { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<todoData> todoData { get; set; }
        public virtual DbSet<aniDataAll> aniDataAll { get; set; }
        public virtual DbSet<boardUser> boardUser { get; set; }
        public virtual DbSet<MsgUser> MsgUser { get; set; }
        public virtual DbSet<aniDataPicOne> aniDataPicOne { get; set; }
        public virtual DbSet<aniDataPicOne2> aniDataPicOne2 { get; set; }
        public virtual DbSet<aniDataPic> aniDataPic { get; set; }
        public virtual DbSet<followAni> followAni { get; set; }
    }
}
