//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjPetAdoption.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remind
    {
        public int remindID { get; set; }
        public string remind_userID { get; set; }
        public string remindFollow { get; set; }
        public string remindTodo { get; set; }
        public string remindMsg { get; set; }
        public string remindSearch { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
