//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjPetAdoption.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shelter
    {
        public int shelterID { get; set; }
        public Nullable<int> shelterName { get; set; }
        public string shelterLocation { get; set; }
        public string shelter_mapID { get; set; }
        public string shelterPhone { get; set; }
        public string shelterURL { get; set; }
        public string shelterContent { get; set; }
        public string shelterPic { get; set; }
    }
}
